<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.wmt</groupId>
        <artifactId>wmt</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>wmt-module-pfb</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>普惠金融小程序进件（PFB-API /pfb-api）</description>

    <dependencies>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-module-system</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-module-infra</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-biz-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-biz-ip</artifactId>
        </dependency>

        <dependency>
            <groupId>com.wmt</groupId>
            <artifactId>wmt-spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
