version: "3.9"

services:
  ahzx-wmt-svc:
    image: wmtserver:v1-6
    container_name: ahzx-wmt-svc
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom"
      # 你后续会提供 application-ahtest 专属配置，这里直接切换 profile
      ARGS: "--spring.profiles.active=ahtest"
    ports:
      - "48080:48080"
    volumes:
      - /data/ahc/logs:/root/logs

